Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array=np.empty((2,2))
print("Empty array(2X2):\n",empty_array)

#Initialize an all one array with size 4X2
ones_array=np.ones((4,2))
print("\nAll one array(4X2):\n ",ones_array)

#Return a new array of given shape and type, filled with fill value
fill_value=5
shape=(3,3)
filled_value=np.full(shape,fill_value)
print("\nFilled array:\n",filled_value)

#Return a new array of zeros with same shape and type as a given array
given_array=np.array([[1,2,3],[4,5,6]])
zeros_array=np.zeros_like(given_array)
print("\nZeros array:\n",zeros_array)

#Return a new array of ones with same shape and type as a given array
ones_array=np.ones_like(given_array)
print("\nOnes array:\n",ones_array)

#For an existing list new_list = [1,2,3,4] convert to an numpy array
new_list=[1,2,3,4]
numpy_array=np.array(new_list)
print("\nConverted NumPy array from list:\n",numpy_array)





Empty array(2X2):
 [[4.82436583e-310 0.00000000e+000]
 [6.52242187e-310 6.52240072e-310]]

All one array(4X2):
  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Zeros array:
 [[0 0 0]
 [0 0 0]]

Ones array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#Create an array with values ranging from 10 to 49
array_range=np.arange(10,50)
print("Array with values ranging from 10 to 49: ",array_range)

#Create a 3X3 matrix with values ranging from 0 to 8
array_matrix=np.arange(9).reshape(3,3)
print("\n3X3 matrix with values ranging from 0 to 8:\n ",array_matrix)

#Create a 3X3 identity matrix.
identity_matrix=np.eye(3)
print("\n3X3 identity matrix:\n",identity_matrix)

#Create a random array of size 30 and find the mean of the array
random_array=np.random.random(30)
mean_value=random_array.mean()
print("\nRandom array of size 30:\n",random_array)
print("\nMean of the array:\n",mean_value)

#Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix=np.random.random((10,10))
min_value=random_matrix.min()
max_value=random_matrix.max()
print("\n10X10 array with random values:\n",random_matrix)
print("\nMinimum value:\n",min_value)
print("\nMaximun value:\n",max_value)

#Create a zero array of size 10 and replace 5th element with 1
zero_array=np.zeros(10)
zero_array[4]=1
print("\nZero array of size 10 with 5th element replaced by 1:",zero_array)

#Reverse an array arr = [1,2,0,0,4,0].
array=np.array([1,2,0,0,4,0])
reversed_array=array[::-1]
print("\nReversed array:\n",reversed_array)

#Create a 2d array with 1 on border and 0 inside
border_array=np.ones((5,5))
border_array[1:-1,1:-1]=0
print("\n2D array with 1 on border and 0 inside:\n",border_array)

#Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard_matrix=np.zeros((8,8),dtype=int)
checkerboard_matrix[1::2,::2]=1
checkerboard_matrix[::2,1::2]=1
print("\n8X8 checkerboard pattern:\n",checkerboard_matrix)

Array with values ranging from 10 to 49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3X3 matrix with values ranging from 0 to 8:
  [[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.93233823 0.59515915 0.01524129 0.72619926 0.86451792 0.1213117
 0.59711887 0.82576035 0.77741607 0.35365544 0.59341702 0.01558805
 0.68443884 0.35467013 0.36979913 0.12717918 0.22834021 0.45658884
 0.1259746  0.07291373 0.35440968 0.49597736 0.35649505 0.14637191
 0.49270345 0.90948013 0.38273425 0.49540369 0.07851289 0.69587476]

Mean of the array:
 0.44151970533126167

10X10 array with random values:
 [[0.95424307 0.83624956 0.22381545 0.72243137 0.90353916 0.86947758
  0.66698325 0.91898669 0.46888351 0.791137  ]
 [0.34476058 0.18464292 0.60748896 0.94780093 0.31048704 0.496014
  0.95563705 0.49963261 0.70330482 0.20693869]
 [0.80469266 0.98841873 0.08167637 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [1]:
import numpy as np
#Given array
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
#Add the two array.
add_xy=x+y
print("Addition of x and y:\n",add_xy)

#Subtract the two array.
subtract_xy=x-y
print("\nSubtraction of x and y:\n",subtract_xy)

#Multiply the array with any integers of your choice
multiply_y=y*4
print("\nMultiplication of y by 4:\n",multiply_y)

#Find the square of each element of the array.
square_x=x**2
print("\nSquare of each element in x:\n",square_x)

#Find the dot product between: v(and)w ; x(and)v ; x(and)y
dot_vw=np.dot(v,w)
print("\nDot product of v and w:\n",dot_vw)

dot_xv=np.dot(x,v)
print("\nDot product of x and v:\n",dot_xv)

dot_xy=np.dot(x,y)
print("\nDot product of x and y:\n",dot_xy)

#Concatenate x and y along row and concatenate v and w along column
concatenate_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n",concatenate_xy_row)

concatenate_vw_column = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("\nConcatenate v and w along columns:\n",concatenate_vw_column)

#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
  concatenate_xv=np.concatenate((x,v), axis=0)
  print("\nConcatenate x and v along rows:\n", concatenate_xv)
except ValueError as e:
  print("\nError encountered while concatenating x and v:\n",e)





Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of y by 4:
 [[20 24]
 [28 32]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w:
 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error encountered while concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [2]:
import numpy as np

A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

#Prove A.A−1 = I.
#Calculate the inverse of A
A_inverse=np.linalg.inv(A)
identity_matrix=np.dot(A,A_inverse)
print("A*A^-1:\n", identity_matrix)

#Prove AB ̸= BA.
AB=np.dot(A,B)
BA=np.dot(B,A)

print("\nAB:\n",AB)
print("\nBA:\n",BA)
print("\nAB==BA:\n",np.array_equal(AB,BA))

#Prove (AB)T = BTAT
AB_T=np.transpose(AB)
BT_AT=np.dot(np.transpose(B),np.transpose(A))
# Display results
print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", BT_AT)
# Check if (AB)^T equals B^T A^T
print("\n(AB)^T == B^T A^T:\n", np.array_equal(AB_T,BT_AT))


#• Solve the following system of Linear equation using Inverse Methods.
#2x − 3y + z = −1
# x − y + 2z = −3
#3x + y − z = 9
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A)
x=np.dot(A_inverse,B)
print("\nSolution for the system of linear equations(x,y,z):\n",x)




A*A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB==BA:
 False

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

(AB)^T == B^T A^T:
 True

Solution for the system of linear equations(x,y,z):
 [ 2.  1. -2.]
